fluidPage(
theme = shinytheme("flatly"),
navbarPage(title="Tomato seedlings screen", inverse=F,
# start tabPanel # 1
tabPanel("Background Information",icon = icon("book"),
sidebarPanel(
fluidRow(
"This Application was build to allow further exploration of the natural variation in salt stress response of tomato seedlings collected from Galapagos islands.",br(), br(), 

"This Application was developed to complement the manuscript entitled",br(),
"YVELINE'S AWESOME MANUSCRIPT", br(),
"Currently submitted for revision", 
br(), br(),
downloadButton("dataAll", label="Download underlying data")
)),
mainPanel(
navbarPage(title="",
tabPanel("Experimental Set-Up", icon = icon("flask"),
helpText("Add the methodology here - maybe include a figure with set up - if already made")),
tabPanel("Traits", icon = icon("key"),
helpText("Here provide the trait descriptions - how they were calculated and using which tools"))))
# end tabPanel # 1
),
# start tabPanel # 2
tabPanel("Compare Individual Lines", icon=icon("leaf"),
sidebarPanel(
fluidRow(
helpText("Select genotypes to compare their salinity tolerance", br(), br(), "The boxplots represent the selected phenotype of eight chosen accessions, and the letters above the graphs represent the significant groups as calculated using Tukey pair-wise comparison with p-value < 0.05.", br(), br(),
strong("DISCLAIMER:"), "As the results presented in here are based only on few biological replicates, the significant differences between the accessions should be interpreted with caution."),
uiOutput("Select_trait_for_anova"),
uiOutput("Select_condition_for_anova"),
uiOutput("Select_genotype_for_anova"),
hr(),
checkboxInput("ANOVA_background", "Remove background?"),
checkboxInput("ANOVA_grid", "Remove major grid lines?"),
selectizeInput("ANOVA_graph_type", "Graph type:", choices = c("Box plot", "Bar graph", "Scatter plot"), selected = "Box plot"),
uiOutput("ANOVA_bar_error")
)),
mainPanel(
verbatimTextOutput("ANOVA_message"),
plotOutput("plot2a"),
verbatimTextOutput("Tukey_message"),
uiOutput("Download_ANOVA_table"),
dataTableOutput("Table1")) 
# end tabPanel # 2
),
# start tabPanel # 3
tabPanel("Examine correlations between individual traits", icon=icon("search-plus"),
  navbarPage("",
      tabPanel("General Correlations",
               sidebarPanel(
                 selectInput("Trait_corr_graph_biggie", label=("Select traits to be included in the correlation analysis"), choices=list(
                   "Days to germination" = "relative_DG", "Days to leaf 4 emergence" = "relative_DL4", "Leaf number increase (from start of treatment) Relative" = "relative_LN", 
                   "Root Length at Control Conditions" = "control_RL", "Root Length at Salt Stress Conditions" = "salt_RL", "Root Length Relative" = "relative_RL",
                   "Shoot Length at Control Conditions" = "control_SL", "Shoot Length at Salt Stress Conditions" = "salt_SL", "Shoot Length Relative" = "relative_SL",
                   "Shoot Thickness at Control Conditions" = "control_ST", "Shoot Thickness at Salt Stress Conditions" = "salt_ST", "Shoot Thickness Relative" = "relative_ST",
                   "Root Fresh Mass at Control Conditions" = "control_RFM", "Root Fresh Mass at Salt Stress Conditions" = "salt_RFM", "Root Fresh Mass Relative" = "relative_RFM",
                   "Shoot Fresh Mass at Control Conditions" = "control_SFM", "Shoot Fresh Mass  at Salt Stress Conditions" = "salt_SFM", "Shoot Fresh Mass Relative" = "relative_SFM",
                   "Total Fresh Mass at Control Conditions" = "control_TFM", "Total Fresh Mass at Salt Stress Conditions" = "salt_TFM", "Total Fresh Mass Relative" = "relative_TFM",
                   "Root Dry Mass at Control Conditions" = "control_RDM", "Root Dry Mass at Salt Stress Conditions" = "salt_RDM", "Root Dry Mass Relative" = "relative_RDM",
                   "Shoot Dry Mass at Control Conditions" = "control_SDM", "Shoot Dry Mass at Salt Stress Conditions" = "salt_SDM", "Shoot Dry Mass Relative" = "relative_SDM",
                   "Total Dry Mass at Control Conditions" = "control_TDM", "Total Dry Mass at Salt Stress Conditions" = "salt_TDM", "Total Dry Mass Relative" = "relative_TDM",
                   "Water Content at Control Conditions" = "control_WC", "Water Content at Salt Stress Conditions" = "salt_WC", "Water Content Relative" = "relative_WC",
                   "Water Concentration at Control Conditions" = "control_WCn", "Water Concentration at Salt Stress Conditions" = "salt_WCn", "Water Concentration Relative" = "relative_WCn",
                   "Green Pixel Count (initial) at Control Conditions" = "control_GPI", "Green Pixel Count (initial) at Salt Stress Conditions" = "salt_GPI", "Green Pixel Count (initial) Relative" = "relative_GPI",
                   "Green Pixel Count (final) at Control Conditions" = "control_GPF", "Green Pixel Count (final) at Salt Stress Conditions" = "salt_GPF", "Green Pixel Count (final) Relative" = "relative_GPF",
                   "Green Pixel Difference (Final - Initial) at Control Conditions" = "control_dGP", "Green Pixel Difference (Final - Initial) at Salt Stress Conditions" = "salt_dGP", "Green Pixel Difference (Final - Initial) Relative" = "relative_dGP",
                   "Leaf 4 Fresh Mass at Control Conditions" = "control_L4FM", "Leaf 4 Fresh Mass at Salt Stress Conditions" = "salt_L4FM", "Leaf 4 Fresh Mass Relative" = "relative_L4FM",
                   "Leaf 4 Dry Mass at Control Conditions" = "control_L4DM", "Leaf 4 Dry Mass at Salt Stress Conditions" = "salt_L4DM", "Leaf 4 Dry Mass Relative" = "relative_L4DM",
                   "Leaf 4 Area at Control Conditions" = "control_L4A", "Leaf 4 Area at Salt Stress Conditions" = "salt_L4A", "Leaf 4 Area Relative" = "relative_L4A",
                   "Root [Na+] accumulation at Control Conditions" = "control_RNa", "Root [Na+] accumulation at Salt Stress Conditions" = "salt_RNa", "Root [Na+] accumulation Relative" = "relative_RNa",
                   "Root [K+] accumulation at Control Conditions" = "control_RK", "Root [K+] accumulation at Salt Stress Conditions" = "salt_RK", "Root [K+] accumulation Relative" = "relative_RK",
                   "Leaf [Na+] accumulation at Control Conditions" = "control_LNa", "Leaf [Na+] accumulation at Salt Stress Conditions" = "salt_LNa", "Leaf [Na+] accumulation Relative" = "relative_LNa",
                   "Leaf [K+] accumulation at Control Conditions" = "control_LK", "Leaf [K+] accumulation at Salt Stress Conditions" = "salt_LK", "Leaf [K+] accumulation Relative" = "relative_LK",
                   "Leaf Succulence at Control Conditions" = "control_LeafSucculence", "Leaf Succulence at Salt Stress Conditions" = "salt_LeafSucculence", "Leaf Succulence Relative" = "relative_LeafSucculence",
                   "Leaf Perimeter at Control Conditions" = "control_LeafPerimeter", "Leaf Perimeter at Salt Stress Conditions" = "salt_LeafPerimeter", "Leaf Perimeter Relative" = "relative_LeafPerimeter",
                   "Leaf Vertucal Length at Control Conditions" = "control_LeafVertLength", "Leaf Vertucal Length at Salt Stress Conditions" = "salt_LeafVertLength", "Leaf Vertucal Length Relative" = "relative_LeafVertLength",
                   "Leaf Horizontal Width at Control Conditions" = "control_LeafHorizWidth", "Leaf Horizontal Width at Salt Stress Conditions" = "salt_LeafHorizWidth", "Leaf Horizontal Width Relative" = "relative_LeafHorizWidth",
                   "Leaf Elongation Factor at Control Conditions" = "control_LeafElongationFactor", "Leaf Elongation Factor at Salt Stress Conditions" = "salt_LeafElongationFactor", "Leaf Elongation Factor Relative" = "relative_LeafElongationFactor"), multiple = T, selected = c("control_LNa", "salt_LNa", "control_LK", "salt_LK", "control_dGP", "salt_dGP")),
                 selectInput("corrplotMethod", "Plot Method:", choices = c("circle", "square", "ellipse", "number", "shade", "color", "pie")),
                 selectInput("corType", "Plot Type:", choices = c("full", "lower", "upper")),
                 selectInput("corOrder", "Order the lables by:", choices = list("Original order" = "original","Angular order of eigenvectors" = "AOE", "First Principal Component order"  = "FPC", "Hierarchical clustering order"  = "hclust", "Alphabetical order" = "alphabet"))
               ),
               mainPanel(
                 plotOutput("BIG_correlation_graph"),
                 downloadButton("dwnldCorr", "Download correlation table"),
                 dataTableOutput("BIG_cor_table")
               )
               ),       
      tabPanel("Scatter plots",
        sidebarPanel(
        fluidRow(
helpText("In this tab you can explore the correlations between individual traits. The values representing individual lines are based on the average calculated per accession per condition. The names of the lines are plotted next to the points representing the individual line. The Pearson correlation coefficient (r) and p-value are plotted above the graphs", br(),
"We hope that those correlation graphs will be helpful to select accessions showing extreme phenotypes, that can be used in, for example for bulked segregant analysis or in depth individual study of the specific lines"),
selectInput("Trait_cor1", label=("Trait 1"), choices=list(
  "Days to germination" = "relative_DG", "Days to leaf 4 emergence" = "relative_DL4", "Leaf number increase (from start of treatment) Relative" = "relative_LN", 
  "Root Length at Control Conditions" = "control_RL", "Root Length at Salt Stress Conditions" = "salt_RL", "Root Length Relative" = "relative_RL",
  "Shoot Length at Control Conditions" = "control_SL", "Shoot Length at Salt Stress Conditions" = "salt_SL", "Shoot Length Relative" = "relative_SL",
  "Shoot Thickness at Control Conditions" = "control_ST", "Shoot Thickness at Salt Stress Conditions" = "salt_ST", "Shoot Thickness Relative" = "relative_ST",
  "Root Fresh Mass at Control Conditions" = "control_RFM", "Root Fresh Mass at Salt Stress Conditions" = "salt_RFM", "Root Fresh Mass Relative" = "relative_RFM",
  "Shoot Fresh Mass at Control Conditions" = "control_SFM", "Shoot Fresh Mass  at Salt Stress Conditions" = "salt_SFM", "Shoot Fresh Mass Relative" = "relative_SFM",
  "Total Fresh Mass at Control Conditions" = "control_TFM", "Total Fresh Mass at Salt Stress Conditions" = "salt_TFM", "Total Fresh Mass Relative" = "relative_TFM",
  "Root Dry Mass at Control Conditions" = "control_RDM", "Root Dry Mass at Salt Stress Conditions" = "salt_RDM", "Root Dry Mass Relative" = "relative_RDM",
  "Shoot Dry Mass at Control Conditions" = "control_SDM", "Shoot Dry Mass at Salt Stress Conditions" = "salt_SDM", "Shoot Dry Mass Relative" = "relative_SDM",
  "Total Dry Mass at Control Conditions" = "control_TDM", "Total Dry Mass at Salt Stress Conditions" = "salt_TDM", "Total Dry Mass Relative" = "relative_TDM",
  "Water Content at Control Conditions" = "control_WC", "Water Content at Salt Stress Conditions" = "salt_WC", "Water Content Relative" = "relative_WC",
  "Water Concentration at Control Conditions" = "control_WCn", "Water Concentration at Salt Stress Conditions" = "salt_WCn", "Water Concentration Relative" = "relative_WCn",
  "Green Pixel Count (initial) at Control Conditions" = "control_GPI", "Green Pixel Count (initial) at Salt Stress Conditions" = "salt_GPI", "Green Pixel Count (initial) Relative" = "relative_GPI",
  "Green Pixel Count (final) at Control Conditions" = "control_GPF", "Green Pixel Count (final) at Salt Stress Conditions" = "salt_GPF", "Green Pixel Count (final) Relative" = "relative_GPF",
  "Green Pixel Difference (Final - Initial) at Control Conditions" = "control_dGP", "Green Pixel Difference (Final - Initial) at Salt Stress Conditions" = "salt_dGP", "Green Pixel Difference (Final - Initial) Relative" = "relative_dGP",
  "Leaf 4 Fresh Mass at Control Conditions" = "control_L4FM", "Leaf 4 Fresh Mass at Salt Stress Conditions" = "salt_L4FM", "Leaf 4 Fresh Mass Relative" = "relative_L4FM",
  "Leaf 4 Dry Mass at Control Conditions" = "control_L4DM", "Leaf 4 Dry Mass at Salt Stress Conditions" = "salt_L4DM", "Leaf 4 Dry Mass Relative" = "relative_L4DM",
  "Leaf 4 Area at Control Conditions" = "control_L4A", "Leaf 4 Area at Salt Stress Conditions" = "salt_L4A", "Leaf 4 Area Relative" = "relative_L4A",
  "Root [Na+] accumulation at Control Conditions" = "control_RNa", "Root [Na+] accumulation at Salt Stress Conditions" = "salt_RNa", "Root [Na+] accumulation Relative" = "relative_RNa",
  "Root [K+] accumulation at Control Conditions" = "control_RK", "Root [K+] accumulation at Salt Stress Conditions" = "salt_RK", "Root [K+] accumulation Relative" = "relative_RK",
  "Leaf [Na+] accumulation at Control Conditions" = "control_LNa", "Leaf [Na+] accumulation at Salt Stress Conditions" = "salt_LNa", "Leaf [Na+] accumulation Relative" = "relative_LNa",
  "Leaf [K+] accumulation at Control Conditions" = "control_LK", "Leaf [K+] accumulation at Salt Stress Conditions" = "salt_LK", "Leaf [K+] accumulation Relative" = "relative_LK",
  "Leaf Succulence at Control Conditions" = "control_LeafSucculence", "Leaf Succulence at Salt Stress Conditions" = "salt_LeafSucculence", "Leaf Succulence Relative" = "relative_LeafSucculence",
  "Leaf Perimeter at Control Conditions" = "control_LeafPerimeter", "Leaf Perimeter at Salt Stress Conditions" = "salt_LeafPerimeter", "Leaf Perimeter Relative" = "relative_LeafPerimeter",
  "Leaf Vertucal Length at Control Conditions" = "control_LeafVertLength", "Leaf Vertucal Length at Salt Stress Conditions" = "salt_LeafVertLength", "Leaf Vertucal Length Relative" = "relative_LeafVertLength",
  "Leaf Horizontal Width at Control Conditions" = "control_LeafHorizWidth", "Leaf Horizontal Width at Salt Stress Conditions" = "salt_LeafHorizWidth", "Leaf Horizontal Width Relative" = "relative_LeafHorizWidth",
  "Leaf Elongation Factor at Control Conditions" = "control_LeafElongationFactor", "Leaf Elongation Factor at Salt Stress Conditions" = "salt_LeafElongationFactor", "Leaf Elongation Factor Relative" = "relative_LeafElongationFactor"), selected = "salt_LNa"),
selectInput("Trait_cor2", label=("Trait 2"), choices=list(
  "Days to germination" = "relative_DG", "Days to leaf 4 emergence" = "relative_DL4", "Leaf number increase (from start of treatment) Relative" = "relative_LN", 
  "Root Length at Control Conditions" = "control_RL", "Root Length at Salt Stress Conditions" = "salt_RL", "Root Length Relative" = "relative_RL",
  "Shoot Length at Control Conditions" = "control_SL", "Shoot Length at Salt Stress Conditions" = "salt_SL", "Shoot Length Relative" = "relative_SL",
  "Shoot Thickness at Control Conditions" = "control_ST", "Shoot Thickness at Salt Stress Conditions" = "salt_ST", "Shoot Thickness Relative" = "relative_ST",
  "Root Fresh Mass at Control Conditions" = "control_RFM", "Root Fresh Mass at Salt Stress Conditions" = "salt_RFM", "Root Fresh Mass Relative" = "relative_RFM",
  "Shoot Fresh Mass at Control Conditions" = "control_SFM", "Shoot Fresh Mass  at Salt Stress Conditions" = "salt_SFM", "Shoot Fresh Mass Relative" = "relative_SFM",
  "Total Fresh Mass at Control Conditions" = "control_TFM", "Total Fresh Mass at Salt Stress Conditions" = "salt_TFM", "Total Fresh Mass Relative" = "relative_TFM",
  "Root Dry Mass at Control Conditions" = "control_RDM", "Root Dry Mass at Salt Stress Conditions" = "salt_RDM", "Root Dry Mass Relative" = "relative_RDM",
  "Shoot Dry Mass at Control Conditions" = "control_SDM", "Shoot Dry Mass at Salt Stress Conditions" = "salt_SDM", "Shoot Dry Mass Relative" = "relative_SDM",
  "Total Dry Mass at Control Conditions" = "control_TDM", "Total Dry Mass at Salt Stress Conditions" = "salt_TDM", "Total Dry Mass Relative" = "relative_TDM",
  "Water Content at Control Conditions" = "control_WC", "Water Content at Salt Stress Conditions" = "salt_WC", "Water Content Relative" = "relative_WC",
  "Water Concentration at Control Conditions" = "control_WCn", "Water Concentration at Salt Stress Conditions" = "salt_WCn", "Water Concentration Relative" = "relative_WCn",
  "Green Pixel Count (initial) at Control Conditions" = "control_GPI", "Green Pixel Count (initial) at Salt Stress Conditions" = "salt_GPI", "Green Pixel Count (initial) Relative" = "relative_GPI",
  "Green Pixel Count (final) at Control Conditions" = "control_GPF", "Green Pixel Count (final) at Salt Stress Conditions" = "salt_GPF", "Green Pixel Count (final) Relative" = "relative_GPF",
  "Green Pixel Difference (Final - Initial) at Control Conditions" = "control_dGP", "Green Pixel Difference (Final - Initial) at Salt Stress Conditions" = "salt_dGP", "Green Pixel Difference (Final - Initial) Relative" = "relative_dGP",
  "Leaf 4 Fresh Mass at Control Conditions" = "control_L4FM", "Leaf 4 Fresh Mass at Salt Stress Conditions" = "salt_L4FM", "Leaf 4 Fresh Mass Relative" = "relative_L4FM",
  "Leaf 4 Dry Mass at Control Conditions" = "control_L4DM", "Leaf 4 Dry Mass at Salt Stress Conditions" = "salt_L4DM", "Leaf 4 Dry Mass Relative" = "relative_L4DM",
  "Leaf 4 Area at Control Conditions" = "control_L4A", "Leaf 4 Area at Salt Stress Conditions" = "salt_L4A", "Leaf 4 Area Relative" = "relative_L4A",
  "Root [Na+] accumulation at Control Conditions" = "control_RNa", "Root [Na+] accumulation at Salt Stress Conditions" = "salt_RNa", "Root [Na+] accumulation Relative" = "relative_RNa",
  "Root [K+] accumulation at Control Conditions" = "control_RK", "Root [K+] accumulation at Salt Stress Conditions" = "salt_RK", "Root [K+] accumulation Relative" = "relative_RK",
  "Leaf [Na+] accumulation at Control Conditions" = "control_LNa", "Leaf [Na+] accumulation at Salt Stress Conditions" = "salt_LNa", "Leaf [Na+] accumulation Relative" = "relative_LNa",
  "Leaf [K+] accumulation at Control Conditions" = "control_LK", "Leaf [K+] accumulation at Salt Stress Conditions" = "salt_LK", "Leaf [K+] accumulation Relative" = "relative_LK",
  "Leaf Succulence at Control Conditions" = "control_LeafSucculence", "Leaf Succulence at Salt Stress Conditions" = "salt_LeafSucculence", "Leaf Succulence Relative" = "relative_LeafSucculence",
  "Leaf Perimeter at Control Conditions" = "control_LeafPerimeter", "Leaf Perimeter at Salt Stress Conditions" = "salt_LeafPerimeter", "Leaf Perimeter Relative" = "relative_LeafPerimeter",
  "Leaf Vertucal Length at Control Conditions" = "control_LeafVertLength", "Leaf Vertucal Length at Salt Stress Conditions" = "salt_LeafVertLength", "Leaf Vertucal Length Relative" = "relative_LeafVertLength",
  "Leaf Horizontal Width at Control Conditions" = "control_LeafHorizWidth", "Leaf Horizontal Width at Salt Stress Conditions" = "salt_LeafHorizWidth", "Leaf Horizontal Width Relative" = "relative_LeafHorizWidth",
  "Leaf Elongation Factor at Control Conditions" = "control_LeafElongationFactor", "Leaf Elongation Factor at Salt Stress Conditions" = "salt_LeafElongationFactor", "Leaf Elongation Factor Relative" = "relative_LeafElongationFactor"), selected = "control_LNa")
)),
mainPanel(column(4,helpText("The Pearson Correlation coefficient (r) is ", textOutput("corr"))),
          column(4,helpText("The p-value is ",textOutput("corpval"))),
          column(12,plotlyOutput("plot3")))))
# end tabPanel # 3
),
# start tabPanel # 4
tabPanel("Cluster Analysis", icon=icon("magic"),
sidebarPanel(
fluidRow(
helpText("Cluster analysis can be performed for any set of chosen traits. Therefore, in this tab we integrated our dataset so that you can perform your own cluster analysis on the traits of your interest.", br(), br()),
br(),
helpText("Please select three phenotypes that you would like to take into consideration for the cluster analysis.", br(),
"You will see the heat-map of the chosen phenotypes appear in the first tab. The value of the phenotypes is normalized with z-Fisher transformation, so the color scale is normalized for each phenotype"),
selectizeInput("Clust_traits", label="Traits", choices=list(
  "Days to germination" = "relative_DG", "Days to leaf 4 emergence" = "relative_DL4", "Leaf number increase (from start of treatment) Relative" = "relative_LN", 
  "Root Length at Control Conditions" = "control_RL", "Root Length at Salt Stress Conditions" = "salt_RL", "Root Length Relative" = "relative_RL",
  "Shoot Length at Control Conditions" = "control_SL", "Shoot Length at Salt Stress Conditions" = "salt_SL", "Shoot Length Relative" = "relative_SL",
  "Shoot Thickness at Control Conditions" = "control_ST", "Shoot Thickness at Salt Stress Conditions" = "salt_ST", "Shoot Thickness Relative" = "relative_ST",
  "Root Fresh Mass at Control Conditions" = "control_RFM", "Root Fresh Mass at Salt Stress Conditions" = "salt_RFM", "Root Fresh Mass Relative" = "relative_RFM",
  "Shoot Fresh Mass at Control Conditions" = "control_SFM", "Shoot Fresh Mass  at Salt Stress Conditions" = "salt_SFM", "Shoot Fresh Mass Relative" = "relative_SFM",
  "Total Fresh Mass at Control Conditions" = "control_TFM", "Total Fresh Mass at Salt Stress Conditions" = "salt_TFM", "Total Fresh Mass Relative" = "relative_TFM",
  "Root Dry Mass at Control Conditions" = "control_RDM", "Root Dry Mass at Salt Stress Conditions" = "salt_RDM", "Root Dry Mass Relative" = "relative_RDM",
  "Shoot Dry Mass at Control Conditions" = "control_SDM", "Shoot Dry Mass at Salt Stress Conditions" = "salt_SDM", "Shoot Dry Mass Relative" = "relative_SDM",
  "Total Dry Mass at Control Conditions" = "control_TDM", "Total Dry Mass at Salt Stress Conditions" = "salt_TDM", "Total Dry Mass Relative" = "relative_TDM",
  "Water Content at Control Conditions" = "control_WC", "Water Content at Salt Stress Conditions" = "salt_WC", "Water Content Relative" = "relative_WC",
  "Water Concentration at Control Conditions" = "control_WCn", "Water Concentration at Salt Stress Conditions" = "salt_WCn", "Water Concentration Relative" = "relative_WCn",
  "Green Pixel Count (initial) at Control Conditions" = "control_GPI", "Green Pixel Count (initial) at Salt Stress Conditions" = "salt_GPI", "Green Pixel Count (initial) Relative" = "relative_GPI",
  "Green Pixel Count (final) at Control Conditions" = "control_GPF", "Green Pixel Count (final) at Salt Stress Conditions" = "salt_GPF", "Green Pixel Count (final) Relative" = "relative_GPF",
  "Green Pixel Difference (Final - Initial) at Control Conditions" = "control_dGP", "Green Pixel Difference (Final - Initial) at Salt Stress Conditions" = "salt_dGP", "Green Pixel Difference (Final - Initial) Relative" = "relative_dGP",
  "Leaf 4 Fresh Mass at Control Conditions" = "control_L4FM", "Leaf 4 Fresh Mass at Salt Stress Conditions" = "salt_L4FM", "Leaf 4 Fresh Mass Relative" = "relative_L4FM",
  "Leaf 4 Dry Mass at Control Conditions" = "control_L4DM", "Leaf 4 Dry Mass at Salt Stress Conditions" = "salt_L4DM", "Leaf 4 Dry Mass Relative" = "relative_L4DM",
  "Leaf 4 Area at Control Conditions" = "control_L4A", "Leaf 4 Area at Salt Stress Conditions" = "salt_L4A", "Leaf 4 Area Relative" = "relative_L4A",
  "Root [Na+] accumulation at Control Conditions" = "control_RNa", "Root [Na+] accumulation at Salt Stress Conditions" = "salt_RNa", "Root [Na+] accumulation Relative" = "relative_RNa",
  "Root [K+] accumulation at Control Conditions" = "control_RK", "Root [K+] accumulation at Salt Stress Conditions" = "salt_RK", "Root [K+] accumulation Relative" = "relative_RK",
  "Leaf [Na+] accumulation at Control Conditions" = "control_LNa", "Leaf [Na+] accumulation at Salt Stress Conditions" = "salt_LNa", "Leaf [Na+] accumulation Relative" = "relative_LNa",
  "Leaf [K+] accumulation at Control Conditions" = "control_LK", "Leaf [K+] accumulation at Salt Stress Conditions" = "salt_LK", "Leaf [K+] accumulation Relative" = "relative_LK",
  "Leaf Succulence at Control Conditions" = "control_LeafSucculence", "Leaf Succulence at Salt Stress Conditions" = "salt_LeafSucculence", "Leaf Succulence Relative" = "relative_LeafSucculence",
  "Leaf Perimeter at Control Conditions" = "control_LeafPerimeter", "Leaf Perimeter at Salt Stress Conditions" = "salt_LeafPerimeter", "Leaf Perimeter Relative" = "relative_LeafPerimeter",
  "Leaf Vertucal Length at Control Conditions" = "control_LeafVertLength", "Leaf Vertucal Length at Salt Stress Conditions" = "salt_LeafVertLength", "Leaf Vertucal Length Relative" = "relative_LeafVertLength",
  "Leaf Horizontal Width at Control Conditions" = "control_LeafHorizWidth", "Leaf Horizontal Width at Salt Stress Conditions" = "salt_LeafHorizWidth", "Leaf Horizontal Width Relative" = "relative_LeafHorizWidth",
  "Leaf Elongation Factor at Control Conditions" = "control_LeafElongationFactor", "Leaf Elongation Factor at Salt Stress Conditions" = "salt_LeafElongationFactor", "Leaf Elongation Factor Relative" = "relative_LeafElongationFactor"),
  multiple=T, selected = c("relative_RNa", "relative_RK", "relative_LNa")),
br(),
helpText("Have a look at the dendrogram by clicking on the tab >> Dendrogram << and determine the value which should be used for splitting the accessions into individual clusters.", br(), br(),
strong("ALERT:"), "Please note that if you chose too many clusters this analysis will not be informative and the subsequent post-hoc analysis will not be possible. We advise for the optimal number of clusters between three to ten.", br(), br(),
"Below please enter the value at which you wish to cut the dendrogram - make sure to enter ONLY numerical values. IF you wish to enter values < 1, please use dot - as in 0.01."),
textInput("tree_cut", label="Cut tree at", value="4"),
br(),
helpText("Download the data to examine which accessions belong to which cluster"),
downloadButton("dwnldClust", label = "Download Cluster data")
)),
mainPanel(
navbarPage(title="",
tabPanel("Clustering Heat Map",
      helpText("This graph represents the clustering of the lines based on three selected traits. The colors represent the phenotype value which has been normalized per trait with Z-Fisher transformation. Please note that the data per accession is based on the average trait value collected from 4 replicas only. "),
      plotOutput("HotHeatMap", height = 800),
      helpText("The below graph represents a dendrogram of the accessions and how they are clustered based on the selected traits in", strong("Step1"),". The accessions are clustered using Ward linkage method and the x-axis is represents the distance between the individual accessions."),
      verbatimTextOutput("Cluster_message"),
      plotOutput("ClusterTree")),
tabPanel("Cluster Validation",
         strong("DISCLAIMER:"), "Note that the differences between the clusters may be due to the unequal distribution of the accessions between the samples. Therefore, the results presented in here should be interpreted with caution.", br(),br(),
         selectInput("Clust_test", label="chose a trait to test", choices=list(
           "Days to germination" = "relative_DG", "Days to leaf 4 emergence" = "relative_DL4", "Leaf number increase (from start of treatment) Relative" = "relative_LN", 
           "Root Length at Control Conditions" = "control_RL", "Root Length at Salt Stress Conditions" = "salt_RL", "Root Length Relative" = "relative_RL",
           "Shoot Length at Control Conditions" = "control_SL", "Shoot Length at Salt Stress Conditions" = "salt_SL", "Shoot Length Relative" = "relative_SL",
           "Shoot Thickness at Control Conditions" = "control_ST", "Shoot Thickness at Salt Stress Conditions" = "salt_ST", "Shoot Thickness Relative" = "relative_ST",
           "Root Fresh Mass at Control Conditions" = "control_RFM", "Root Fresh Mass at Salt Stress Conditions" = "salt_RFM", "Root Fresh Mass Relative" = "relative_RFM",
           "Shoot Fresh Mass at Control Conditions" = "control_SFM", "Shoot Fresh Mass  at Salt Stress Conditions" = "salt_SFM", "Shoot Fresh Mass Relative" = "relative_SFM",
           "Total Fresh Mass at Control Conditions" = "control_TFM", "Total Fresh Mass at Salt Stress Conditions" = "salt_TFM", "Total Fresh Mass Relative" = "relative_TFM",
           "Root Dry Mass at Control Conditions" = "control_RDM", "Root Dry Mass at Salt Stress Conditions" = "salt_RDM", "Root Dry Mass Relative" = "relative_RDM",
           "Shoot Dry Mass at Control Conditions" = "control_SDM", "Shoot Dry Mass at Salt Stress Conditions" = "salt_SDM", "Shoot Dry Mass Relative" = "relative_SDM",
           "Total Dry Mass at Control Conditions" = "control_TDM", "Total Dry Mass at Salt Stress Conditions" = "salt_TDM", "Total Dry Mass Relative" = "relative_TDM",
           "Water Content at Control Conditions" = "control_WC", "Water Content at Salt Stress Conditions" = "salt_WC", "Water Content Relative" = "relative_WC",
           "Water Concentration at Control Conditions" = "control_WCn", "Water Concentration at Salt Stress Conditions" = "salt_WCn", "Water Concentration Relative" = "relative_WCn",
           "Green Pixel Count (initial) at Control Conditions" = "control_GPI", "Green Pixel Count (initial) at Salt Stress Conditions" = "salt_GPI", "Green Pixel Count (initial) Relative" = "relative_GPI",
           "Green Pixel Count (final) at Control Conditions" = "control_GPF", "Green Pixel Count (final) at Salt Stress Conditions" = "salt_GPF", "Green Pixel Count (final) Relative" = "relative_GPF",
           "Green Pixel Difference (Final - Initial) at Control Conditions" = "control_dGP", "Green Pixel Difference (Final - Initial) at Salt Stress Conditions" = "salt_dGP", "Green Pixel Difference (Final - Initial) Relative" = "relative_dGP",
           "Leaf 4 Fresh Mass at Control Conditions" = "control_L4FM", "Leaf 4 Fresh Mass at Salt Stress Conditions" = "salt_L4FM", "Leaf 4 Fresh Mass Relative" = "relative_L4FM",
           "Leaf 4 Dry Mass at Control Conditions" = "control_L4DM", "Leaf 4 Dry Mass at Salt Stress Conditions" = "salt_L4DM", "Leaf 4 Dry Mass Relative" = "relative_L4DM",
           "Leaf 4 Area at Control Conditions" = "control_L4A", "Leaf 4 Area at Salt Stress Conditions" = "salt_L4A", "Leaf 4 Area Relative" = "relative_L4A",
           "Root [Na+] accumulation at Control Conditions" = "control_RNa", "Root [Na+] accumulation at Salt Stress Conditions" = "salt_RNa", "Root [Na+] accumulation Relative" = "relative_RNa",
           "Root [K+] accumulation at Control Conditions" = "control_RK", "Root [K+] accumulation at Salt Stress Conditions" = "salt_RK", "Root [K+] accumulation Relative" = "relative_RK",
           "Leaf [Na+] accumulation at Control Conditions" = "control_LNa", "Leaf [Na+] accumulation at Salt Stress Conditions" = "salt_LNa", "Leaf [Na+] accumulation Relative" = "relative_LNa",
           "Leaf [K+] accumulation at Control Conditions" = "control_LK", "Leaf [K+] accumulation at Salt Stress Conditions" = "salt_LK", "Leaf [K+] accumulation Relative" = "relative_LK",
           "Leaf Succulence at Control Conditions" = "control_LeafSucculence", "Leaf Succulence at Salt Stress Conditions" = "salt_LeafSucculence", "Leaf Succulence Relative" = "relative_LeafSucculence",
           "Leaf Perimeter at Control Conditions" = "control_LeafPerimeter", "Leaf Perimeter at Salt Stress Conditions" = "salt_LeafPerimeter", "Leaf Perimeter Relative" = "relative_LeafPerimeter",
           "Leaf Vertucal Length at Control Conditions" = "control_LeafVertLength", "Leaf Vertucal Length at Salt Stress Conditions" = "salt_LeafVertLength", "Leaf Vertucal Length Relative" = "relative_LeafVertLength",
           "Leaf Horizontal Width at Control Conditions" = "control_LeafHorizWidth", "Leaf Horizontal Width at Salt Stress Conditions" = "salt_LeafHorizWidth", "Leaf Horizontal Width Relative" = "relative_LeafHorizWidth",
           "Leaf Elongation Factor at Control Conditions" = "control_LeafElongationFactor", "Leaf Elongation Factor at Salt Stress Conditions" = "salt_LeafElongationFactor", "Leaf Elongation Factor Relative" = "relative_LeafElongationFactor"),
           selected = "salt_LNa"),   
      br(),
      plotOutput("HotANOVA"),
helpText("The boxplot represents the phenotype value per cluster. The average values per accessions were pulled depending on the cluter cut-off value. The letters above the graph represent the significant groups as calculated using Tukey pair-wise comparison with p-value < 0.05.")))
)))
# end of tabPanel#4
)